### PR TITLE
Upgrade hyperhtml-element version

### LINKED ISSUE #31: update to hyperHtml element 3.1+

### PR DESCRIPTION
**Pull request by SheepFromHeaven**
resolves #31

### CODE REVIEW

**Comment by jurekbarth** [comment]
@SheepFromHeaven are tests failing locally too?

**Comment by timomayer** [comment]
I am sure there is more to do. I tried the same with version 3.1.0 and it broke bio element

**Comment by SheepFromHeaven** [comment]
@jurekbarth @timomayer it's not breaking biotope element, just the tests. It seems that our jsdom cannot handle CustomEvents -.-

**Comment by SheepFromHeaven** [comment]
Working on it

**Comment by SheepFromHeaven** [comment]
@biotope/core-enforcer up and running again. This PR will also resolve #57

**Pull request merged**
