### PR TITLE
Demonstrated approach for component wrappers; used re-rendering on ch…

### PR DESCRIPTION
**Pull request by marwesfur**
Hi all,

here is a suggestion how ComponentWrappers could be implemented. The idea is basically to take a component and create a subclass on the fly. This is somehow complicated by TypeScript differentiating between classes as types and class constructor functions and allowing only the latter  as return values of functions [^1].

I favoured this approach over inheritance, as imo it should  be possible to combine different wrappers such as `withOnChildrenUpdated` and `withReduxConnection`.

I'm not 100% satisfied how this turned out and it's far from being done. Maybe you have some creative ideas to squeeze this into TypeScript's syntax :)

~~~
export class Slider extends BioElement<SliderProps, SliderState> {
    constructor() {
        super();
        this.attachShadow({ mode: 'open' });

        this.onNextSlide = this.onNextSlide.bind(this);
        this.onPrevSlide = this.onPrevSlide.bind(this);
        this.onSelectSlide = this.onSelectSlide.bind(this);
    }

	...
}

withOnChildrenUpdated(Slider).define('x-slider');
~~~

[^1]: In plain JavaScript it would have been possible to write `Slider extends withOnChildrenUpdated(BioElement)`

### CODE REVIEW

**Comment by marwesfur** [comment]
ideas keep coming :)

added a "type generator func", that allows for a more symmetrical syntax making this possible: 

~~~~~
export class Slider extends withOnChildrenUpdated(withPropsAndState<SliderProps, SliderState>()) {
    constructor() {
        super();
~~~~~

**Comment by tiagomapmarques** [comment]
Agree with @SheepFromHeaven
Should we move this to the `experimental` repo and close this PR?

**Comment by marwesfur** [comment]
Disagree (at least partially): having an optional mixin for detecting children changes seems cruical for many applications.the other mix in, though, can be considered as "demonstration only"

**Comment by tiagomapmarques** [comment]
@marwesfur IMO if `BioElement` needs that feature (i.e. if it's really that essential), then it shouldn't be a mixin :)

**Comment by marwesfur** [comment]
@tiagomapmarques it is essential for some use cases  - and we should make sure, that the wheel isn't reinvented every time such a case occurs. Otoh, for other cases it is not necessary to react to children updates. Therefore a mixin.
Composition is a well established principle in software engineering. See for example skate.js

**Comment by tiagomapmarques** [comment]
@marwesfur
Yes, composition is great! I'm not arguing that :)
What I'm saying is that it's a worthwhile feature and it's small enough to be in BioElement itself and cause issues to components that dont want to react to children updates. Hence me suggesting that that particular feature may belong to BioElement and not in a composition function.

**Comment by marwesfur** [comment]
Ok, I honestly don't know which costs come with instantiating a mutationObserver, but let's do as you suggest - we can still adjust later on if necessary

**Pull request closed without merging**
